### ISSUE TITLE
PMpatch

### ISSUE THREAD

**Issue by pud469** [OreyM/Hackintosh-Dell-T5810-Xeon-E5-26xx-V3-OpenCore-PowerMac-G5#3]
Not really an issue, but it is possible to disable the MSR lock on this board.  Which would allow to not us the PMpatch in open core and bring native power management.

**Comment by BillDH2k** [comment]
The MSR can be disabled. See [this Reddit post](https://www.reddit.com/r/hackintosh/comments/k3qt2h/dell_t7810_how_to_disable_cfg_lock/).
