### ISSUE TITLE
Successfully installed Bigsur

### ISSUE THREAD

**Issue by noo-hasta** [OreyM/Hackintosh-Dell-T5810-Xeon-E5-26xx-V3-OpenCore-PowerMac-G5#4]
Sorry OreyM I'm a noob here, I don't know how to use github, dont know how to share my little project, so i leave my comment here. I also wanna say Thank You for the Catalina efi folder.

Any how to answer the previous question, T5810 can run bigg sur.  Similar to Catalina, the system recognized the nvme as external. The important thing is that just as opencore mentioned, installation needs to be done on another system than transfer the drive. Otherwise you will be stuck at the 13 minute mark during installation.
I did test the installation twice, one on ssd and one one nvme drive.

**Comment by OreyM** [comment]
Hi. The installation of this assembly was carried out on the nvme disk. It's indeed recognized as external. But there are no installation problems if the BIOS is configured correctly and the rest of the hardware is compatible with MacOS or doesn't create problems.

Last time I was able to install BigSur, but the build was far from perfect. Unfortunately, my project is closed =( My country has a neighbor who started an aggressive war. My project was sold out and the money was sent to our soldiers.
